build-dev:
	docker build -t asia-southeast1-docker.pkg.dev/durable-cursor-409309/kip-agent-creator/fe:$(TAG) .
	docker push asia-southeast1-docker.pkg.dev/durable-cursor-409309/kip-agent-creator/fe:$(TAG)