version: '3.8'

services:
  agent-executor:
    image: superioragents/agent-executor:latest

  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    volumes:
      - ./agent/db/:/app/db
      - ./agent/code:/app/code
      - ./agent/src:/app/src
      - ./agent/scripts:/app/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONPATH=/app
      - SQLITE_PATH=/app/db/superior-agents.db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TXN_SERVICE_URL=http://meta-swap-api:9009
      - RAG_URL=http://rag-api:8080
    command: sleep infinity
    networks:
      - app-network

  meta-swap-api:
    build:
      context: ./meta-swap-api
      dockerfile: Dockerfile
    ports:
      - "9009:9009"
    networks:
      - app-network
    environment:
      - NODE_ENV=development
      - ETH_PRIVATE_KEY=${ETH_PRIVATE_KEY}
      - ETH_RPC_URL=https://eth-protect.rpc.blxrbdn.com
      - PORT=9009
      - SOLANA_RPC_URL=https://api.mainnet-beta.solana.com

  rag-api:
    build:
      context: ./rag-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - PORT=8080
      - NODE_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    
networks:
  app-network:
    driver: bridge